apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_DATABASE
              value: mydb
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql      # nơi MySQL lưu data
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
