apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP              # chỉ cho app trong cluster truy cập
  ports:
    - port: 3306
      targetPort: 3306